server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # È il server stesso, non deve registrarsi
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 # Avvio più rapido in locale